### ISSUE TITLE
[BUG] Dispatch - Unit list - RMB not working

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#152]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

In this [message](https://github.com/SnailyCAD/snaily-cadv4/issues/45#issuecomment-961324652) I describe functionality for RMB for Unit list on Dispatch page. But RMB not working.

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Are you able to elaborate what is not working?

**Comment by pp2amd6** [comment]
> If you press the right mouse button on an entry in the list of units, a menu will be called
If a status code is selected in the menu, the status will change for the officer
If the situation code is selected in the menu and the unit is attached to the call, an entry will be added to the event log
If the situation code is selected in the menu and the unit is NOT attached to the call, then the call will be automatically created (if the checkbox is set) and an entry will be added to the event log

**Comment by Dev-CasperTheGhost** [comment]
This is the current state of that feature. The last one wasn't implemented since it doesn't make sense to me. Unless there's something else that had to be implemented? @pp2amd6 

- ✅ If you press the right mouse button on an entry in the list of units, a menu will be called
- ✅ If a status code is selected in the menu, the status will change for the officer
- ✅ If the situation code is selected in the menu and the unit is attached to the call, an entry will be added to the event log
- ❌ If the situation code is selected in the menu and the unit is NOT attached to the call, then the call will be automatically created (if the checkbox is set) and an entry will be added to the event log

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost Is the functionality not loaded into the repository?

**Comment by Dev-CasperTheGhost** [comment]
Should be

**Comment by pp2amd6** [comment]
> If you press the right mouse button on an entry in the list of units, a menu will be called

Does not work

https://user-images.githubusercontent.com/4976837/142217391-588ba109-d206-462b-9b22-97761bf08682.mp4

**Comment by Dev-CasperTheGhost** [comment]
oohh, you mean there. I thought it was only mean for the ManageCall modal 😅! I'll re-open this issue and implement this feature shortly!
