### ISSUE TITLE
PDF reports not working - file is corrupted

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1836]
### What version of Node.js are you using?

18

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.73.0 fedb678

### Describe the Bug

Clicking on Export button that should generate PDF report of some ticket/arrest report, it generates broken PDF.

### Expected Behavior

When clicking the button, it generates and downloads PDF that can be open and is not distorted.

### To Reproduce

Click on the Export button and open downloaded PDF.

**Comment by casperiv0** [comment]
So, this is most likely an issue that happens when installing the dependencies. Here's a similar issue I had: 
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/53900565/0912d1c5-c1b6-4ff6-bec3-319c74df2dc3)

Are you able to follow [their troubleshooting guide](https://pptr.dev/troubleshooting) and also check if you're receiving an error in the API logs if an error occurs please.

**Comment by casperiv0** [comment]
Also, let me know if you're running SnailyCAD as root user, there are some things that need to be configured in that case. @bartusek27

**Comment by bartusek27** [comment]
I have probably fixed the Puppeteer problem - this should probably be implemented into the docs that I need Chromium for this - also it seems that I have the same problem with root.

**Comment by casperiv0** [comment]
Alright, perfect. Will add a page to the docs later today that explains the root issue & fix for that. It will also include the required dependencies puppeteer requires

**Comment by casperiv0** [comment]
Please update to the very latest version and check this doc page: https://docs.snailycad.org/docs/errors/corrupt-pdf-export
